spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: #PASSWORD#
  jpa:
    generate-ddl: true

productLoad:
  #Locate FOLDER with *.csv files
  path: #ABSOLUTE PATH#
  #Use ISO 8601 Durations format
  period: #PT02H#